README.md
build.sbt
ts-reaktive-testkit-assertj/build.sbt
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/AbstractCompletionStageAssert.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/CompletionStageAssert.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/CompletionStageAssertions.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/FutureShouldComplete.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/FutureShouldFail.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/FutureShouldSucceed.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/JsonNodeAssertions.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/Throwables.java

Also bump to latest scala, because why not.

[0.0.3] Add in assertion classes, touch up readme

---

README.md
build.sbt
ts-reaktive-actors/build.sbt
ts-reaktive-akka/build.sbt
ts-reaktive-akka/src/main/scala/com/tradeshift/reaktive/akka/AbstractActorPublisherWithStash.scala

Add some Java base classes that are currently missing from akka
See akka/akka#20762

Java classes

---

build.sbt
project/plugins.sbt

@alar17 or @ehats , please review

Do not require protoc to be installed

---

build.sbt
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/akka/rest/JacksonMarshallers.java

@ehats  so we keep with the times, and get the nice [performance improvements](http://akka.io/news/2016/08/19/akka-2.4.9-released.html)

Upgrade to akka 2.4.9

---

ts-reaktive-actors/README.md
ts-reaktive-marshal-akka/build.sbt
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/http/HttpFlow.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/http/JSONMarshallers.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/http/XMLMarshallers.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/stream/AaltoReader.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/stream/Base64Decoder.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/stream/ProtocolFilter.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/stream/ProtocolWriter.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/stream/SchemaValidatorFlow.java
ts-reaktive-marshal-akka/src/test/java/com/tradeshift/reaktive/marshal/http/HttpFlowSpec.java
ts-reaktive-marshal-akka/src/test/java/com/tradeshift/reaktive/marshal/stream/Base64DecoderSpec.java
ts-reaktive-marshal-akka/src/test/java/com/tradeshift/reaktive/marshal/stream/ProtocolWriterSpec.java
ts-reaktive-marshal-akka/src/test/java/com/tradeshift/reaktive/marshal/stream/SchemaValidatorSpec.java
ts-reaktive-marshal-akka/src/test/resources/test.xsd
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/Protocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/Reader.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/Writer.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/xml/BodyEventsProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/xml/SelectedTagProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/xml/XMLProtocol.java

- Add "reverse mode" http client, exposing as Flow
- Add ability to do filter and select on protocol flows
- Add ability to do XSD schema validation on an XML flow
- Various new XML protocols to help the above

More streaming http and marshalling additions

---

ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/http/HttpFlow.java
ts-reaktive-marshal-akka/src/test/java/com/tradeshift/reaktive/marshal/http/HttpFlowSpec.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/xml/TagReadProtocol.java
ts-reaktive-marshal/src/test/java/com/tradeshift/reaktive/xml/XMLProtocolSpec.java

This allows users of the flow to take additional actions on e.g. the content type of the response.
@alar17 please review

HttpFlow materializes into HttpResponse, instead of just Done

---

ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/FieldProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/ValueProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/AnyOfProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/CombinedProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/Protocol.java
ts-reaktive-marshal/src/test/java/com/tradeshift/reaktive/json/JSONProtocolSpec.java
ts-reaktive-marshal/src/test/java/com/tradeshift/reaktive/marshal/CombinedProtocolSpec.java
ts-reaktive-marshal/src/test/java/com/tradeshift/reaktive/xml/XMLProtocolSpec.java

As part of that, "alternatively" is renamed to "anyOf". Also touched up some debugging strings so error messages are nice and informative.

Introduce "allOf", as antonym to the existing "alternatively"

---

ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/JSONProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/ObjectProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/ObjectWriteProtocol.java

Add identity object methods for read- or write-only protocol variants

---

README.md
build.sbt
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractCommandHandler.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActor.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/ACL.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/ACLBuilder.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/GroupedUserACL.java
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActorSpec.java
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/acl/ACLSpec.java
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/acl/GroupedUserACLSpec.java
ts-reaktive-actors/src/test/resources/log4j.xml
ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3Restore.java
ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/TestActor.java

Add ability to asynchronously handle commands, and minor cleanups.

---

build.sbt
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActor.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/ACL.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/GroupedUserACL.java
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/acl/ACLSpec.java
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/acl/GroupedUserACLSpec.java
ts-reaktive-marshal-xerces/build.sbt
ts-reaktive-marshal-xerces/src/main/java/com/tradeshift/reaktive/marshal/convert/XMLToJSON.java
ts-reaktive-marshal-xerces/src/test/java/com/tradeshift/reaktive/marshal/convert/XMLToJSONSpec.java
ts-reaktive-marshal-xerces/src/test/resources/com/tradeshift/reaktive/marshal/convert/person1.xml
ts-reaktive-marshal-xerces/src/test/resources/com/tradeshift/reaktive/marshal/convert/person2.xml
ts-reaktive-marshal-xerces/src/test/resources/com/tradeshift/reaktive/marshal/convert/person3.xml
ts-reaktive-marshal-xerces/src/test/resources/com/tradeshift/reaktive/marshal/convert/person4.xml
ts-reaktive-marshal-xerces/src/test/resources/com/tradeshift/reaktive/marshal/convert/sample.xsd
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActor.java

@alar17 please review. We need this to support our existing JS-land validation code.

Write XML to JSON flow that roughtly follows JAXB+Jackson semantics

---

build.sbt
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/akka/UUIDs.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/akka/rest/EventRoute.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/protobuf/EventEnvelopeSerializer.java
ts-reaktive-actors/src/main/protobuf/Query.proto
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/akka/rest/EventRouteIntegrationSpec.java
ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3.java
ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3Backup.java
ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/S3BackupSpec.java
ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/S3RestoreSpec.java
ts-reaktive-cassandra/src/main/java/com/tradeshift/reaktive/cassandra/CassandraSession.java
ts-reaktive-kamon-akka-http/src/main/scala/com/tradeshift/reaktive/kamon/akka/http/HttpServerInstrumentation.scala
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/http/JSONMarshallers.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/http/XMLMarshallers.java
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/DataCenter.java
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/DataCenterForwarder.java
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/Replication.java
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/VisibilityCassandraSession.java
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActor.java
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/io/WebSocketDataCenterClient.java
ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/DataCenterForwarderSpec.java
ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/ReplicatedActorSpec.java

Also move to EventsByTagQuery2, since (1) is deprecated, and akka 2.5 will
promote v2 to be the actual EventsByTagQuery.

Upgrade akka 2.4.17, http 10.0.4, cassandra-query 0.24

---

build.sbt
ts-reaktive-csv/build.sbt
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/CharsetDecoderFlow.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/CharsetEncoderFlow.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/CsvEvent.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/CsvParser.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/CsvSettings.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/CsvTextAggregator.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/CsvWriter.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/marshal/CsvProtocol.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/marshal/MultiReadProtocol.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/marshal/MultiWriteProtocol.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/marshal/NamedColumnReadProtocol.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/marshal/NamedColumnWriteProtocol.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/marshal/StringValueProtocol.java
ts-reaktive-csv/src/main/java/com/tradeshift/reaktive/csv/marshal/ValueProtocol.java
ts-reaktive-csv/src/test/java/com/tradeshift/reaktive/csv/CharsetDecoderFlowSpec.java
ts-reaktive-csv/src/test/java/com/tradeshift/reaktive/csv/CharsetEncoderFlowSpec.java
ts-reaktive-csv/src/test/java/com/tradeshift/reaktive/csv/CsvParserSpec.java
ts-reaktive-csv/src/test/java/com/tradeshift/reaktive/csv/CsvWriterSpec.java
ts-reaktive-csv/src/test/java/com/tradeshift/reaktive/csv/marshal/CsvProtocolSpec.java
ts-reaktive-csv/src/test/java/com/tradeshift/reaktive/csv/marshal/DTO.java
ts-reaktive-csv/src/test/java/com/tradeshift/reaktive/csv/marshal/OptionDTO.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/IterableProtocol.java

...because I got bored.
Includes reading and writing, and read/write marshalling support.

Write a reactive CSV parser

---

build.sbt
ts-reaktive-kamon-akka-client/build.sbt
ts-reaktive-kamon-akka-client/src/main/resources/META-INF/aop.xml
ts-reaktive-kamon-akka-client/src/main/resources/reference.conf
ts-reaktive-kamon-akka-client/src/main/scala/akka/http/impl/engine/client/PoolConductorMonitoring.scala
ts-reaktive-kamon-akka-client/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActorMonitoring.scala

This'l eventually be PR'ed into `kamon-akka-http` once we get it working.

add module for monitoring akka-http client internals

---

build.sbt
ts-reaktive-aws/README.md
ts-reaktive-aws/src/main/scala/com/tradeshift/reaktive/aws/AWSClient.scala
ts-reaktive-aws/src/main/scala/com/tradeshift/reaktive/aws/cluster/ASGClusterExtension.scala
ts-reaktive-aws/src/test/scala/com/tradeshift/reaktive/aws/AWSClientSpec.scala
ts-reaktive-aws/src/test/scala/com/tradeshift/reaktive/aws/cluster/ASGClusterExtensionSpec.scala

Add AWS auto-scaling groups support for akka clustering

Add ts-reaktive-aws module

---

build.sbt
ts-reaktive-replication/src/test/resources/log4j.xml

Migrations are required for this, read [here](
https://github.com/akka/akka-persistence-cassandra#migrations-to-080-and-later
)

Upgrade akka persistence which moves away from materialized views

---

build.sbt
ts-reaktive-cassandra/src/main/java/com/tradeshift/reaktive/cassandra/CassandraSession.java
ts-reaktive-java/src/main/java/com/tradeshift/reaktive/ListenableFutures.java
ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/VisibilityCassandraSession.java

Modify CassandraSession in order to initialize the keyspaces and tables

Add initial statements execution to CassandraSession

---

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActor.java
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActorSpec.java

Otherwise, we may end up firing off several commands from the same state,
each doing different changes assuming they're the only one.

Stash commands that come in while doing another async command

---

build.sbt
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/GroupWhile.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerMetrics.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/singleton/ClusterSingleton.java
ts-reaktive-actors/src/main/resources/reference.conf
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/GroupWhileSpec.java

- MaterializerActor can create a materialized view from a journal
- ClusterSingleton can launch auto-respawning cluster singletons with
reasonable defaults
and these two combine very well.

Add a few utility actors

---

ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActor.java

Classes extending ReplicatedActor may want to refer to its
createReceiveRecover() method multiple times. Currently, this causes the
base class to not work, since its AtomicReference would be created
several times.
By assigning the Receive to a variable, and having the method just
return that, we can invoke it as often as we like (like a scala val).

Allow createReceiveRecover to be invoked multiple times

---

.gitignore
build.sbt
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/CommandHandler.java
ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/http/JSONMarshallers.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/AbstractCommandResultsAssert.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/CommandResultsAssert.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/CommandResultsAssertions.java
ts-reaktive-testkit/src/main/java/com/tradeshift/reaktive/testkit/Await.java

See individual commit messages.

Various small fixes

---

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/ACL.java
ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/acl/ACLSpec.java

See the added test for details.

Simplify vavr expression and fix a whoopsie

---

ts-reaktive-java/src/main/java/com/tradeshift/reaktive/CompletableFutures.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/JSONProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/ObjectWriteProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/FoldProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/IterableProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/IterableProtocolMarker.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/MapProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/OptionProtocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/Protocol.java
ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/SeqProtocol.java
ts-reaktive-marshal/src/test/java/com/tradeshift/reaktive/json/JSONProtocolSpec.java
ts-reaktive-testkit-assertj/src/main/java/com/tradeshift/reaktive/assertj/AbstractCommandResultsAssert.java

See individual commits for comments.

Various fixes

---

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java
ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerMetrics.java
ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/ReplicationIntegrationSpec.java

See individual commit messages for details.

More metrics, and faster unit test

---

ts-reaktive-xsd/src/main/scala/com/tradeshift/reaktive/xsd/Schema.scala
ts-reaktive-xsd/src/test/scala/com/tradeshift/reaktive/xsd/SchemaLoaderSpec.scala

XSD case classes can now be used to determine whether a valid child tag
could potentially occur more than once.
----
#

Add ability for XSD type to report whether a child can be 0..*

---

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java

Providing additional monitoring tags in MaterializerActor was done by calling an overridable method in the constructor which is not a safe approach.
This PR adds a second constructor which can be called with the additional metric tags. The overridable method `getAdditionalMetricTags()` is removed.

Fix additional metric tags problem in MaterializerActor
