ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/cassandra/CassandraLogger.java, ts-reaktive-actors/src/main/resources/reference.conf
Prefix is optional and configurable by system settings. By default value is `reaktive`
@jypma @alar17
=> CassandraLogger prefix made configurable

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/CompletableFutures.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/CompletableFutureSpec.java
Fixed generic type and added a simple unit test for CompletableFutures#sequence.
Without the type change the test results in compilation error
```
method com.tradeshift.reaktive.CompletableFutures.<T>sequence(java.util.Collection<java.util.concurrent.CompletableFuture<? extends T>>) is not applicable
(cannot infer type-variable(s) T
(argument mismatch; java.util.ArrayList<java.util.concurrent.CompletableFuture<java.lang.Integer>> cannot be converted to java.util.Collection<java.util.concurrent.CompletableFuture<? extends T>>))
```
@jypma
=> fixed generic type for CompletableFutures.sequence

ts-reaktive-actors/build.sbt
Bump to prevent version mismatches caused by transitive dependencies.
=> Update Jackson-databind to 2.7.4

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/cassandra/CassandraSession.java, ts-reaktive-testkit/build.sbt, ts-reaktive-testkit/src/main/java/com/tradeshift/reaktive/testkit/Await.java, ts-reaktive-testkit/src/test/java/com/tradeshift/reaktive/testkit/AwaitSpec.java
- Provide a thin Java wrapper around the async CassandraSession
- Add Eventually to do scalatest-like "eventually { ... }" in tests
@ehats @alar17 please review
=> Two unrelated additions

project/plugins.sbt, ts-reaktive-actors/build.sbt, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/akka/rest/EventRoute.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/protobuf/UUIDs.java, ts-reaktive-actors/src/main/protobuf/Query.proto, ts-reaktive-actors/src/main/protobuf/Types.proto, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/akka/rest/EventRouteIntegrationSpec.java
Needed to have something to transmit between datacenters in https://github.com/Tradeshift/ts-reaktive/pull/8 .
=> Adding protobuf definition for EventEnvelope so EventRoute can be concrete

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractState.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/PersistentActorSharding.java, ts-reaktive-marshal-akka/src/test/java/com/tradeshift/reaktive/marshal/http/HttpFlowSpec.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActorSharding.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/TestActor.java
This makes the class a little easier to learn and more flexible.
Clients can do `UUID.fromString` themselves if they know they're putting in UUIDs.
@alar17 can you do a quick review?
=> Have PersistentActorSharding be about String instead of UUID

ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/stream/StaxWriter.java, ts-reaktive-marshal-akka/src/test/java/com/tradeshift/reaktive/marshal/stream/StaxWriterSpec.java
We don't want to enburden all tag protocols with needing to register
and de-register namespaces. It's smarter to have StaxWriter
auto-inject them, so all protocols can just output plain QNames.
=> StaxWriter should auto-create namespaces for StartElement events

build.sbt, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/protobuf/DelimitedProtobufFraming.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/protobuf/DelimitedProtobufFramingSpec.java, ts-reaktive-actors/src/test/resources/log4j.xml, ts-reaktive-backup/build.sbt, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/DropUntilNext.java, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3.java, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3Backup.java, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3Entry.java, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3Restore.java, ts-reaktive-backup/src/main/resources/reference.conf, ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/DropUntilNextSpec.java, ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/S3BackupSpec.java, ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/S3RestoreSpec.java, ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/S3Spec.java, ts-reaktive-backup/src/test/resources/com/tradeshift/reaktive/backup/listresponse.xml, ts-reaktive-backup/src/test/resources/log4j.xml, ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/marshal/StringMarshallable.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/Replication.java
The plan is as follows:
- `S3Backup` continuously reads event stream, batches it up, and writes keys into S3. Also continuously updates the "last written" offset in S3.
- `S3Restore` will list the bucket, (amazon sort it lexographically, so we'll make sure that's in event starting order), and then play back those events into a running instance of `PersistentActorSharding`.
This approach will save all event ordering and information, but lose the cassandra-intenals of when events were written (just like in multi-datacenter replication). That shouldn't be a problem, since proper events would have a real user business timestamp as well, anyways.
Possible alternative, future implementation: `S3Backup` reads events over HTTPS from an `EventRoute`, `S3Restore` plays back events over Websocket to …
=> Backup events to S3, in order to do emergency off-line restore

ts-reaktive-cassandra/src/main/java/com/tradeshift/reaktive/cassandra/CassandraSession.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/VisibilityRepository.java
There's no reason [Row] can't just be mapped by user code functions, so
taking the rowMapper function as explicit argument is unnecessary.
In expectation of further upgrades in https://github.com/Tradeshift/ts-reaktive/pull/53 .
=> Simplify API to help mocking the cassandra session during unit tests

build.sbt, ts-reaktive-actors/build.sbt, ts-reaktive-backup/build.sbt, ts-reaktive-cassandra/build.sbt, ts-reaktive-cassandra/src/test/resources/log4j.xml, ts-reaktive-marshal-akka/src/test/resources/test.xml, ts-reaktive-replication/build.sbt, ts-reaktive-ssl/build.sbt
Upgrading `akka-persistence-cassandra` and `cassandra-all` dependencies.
New version is more reliable because uses new `cassandra-driver-core` and few issues were fixed. Minimum required version of `cassandra-all` for `akka-persistence-cassandra` is 3.8.
Even if there are versions up to 3.11, lowest dependency that doesn't fail with log4j and logback issues for us is 3.9.
Some details:
- [explicit logback in cassandra-all-3.10](https://github.com/apache/cassandra/blob/cassandra-3.10/src/java/org/apache/cassandra/cql3/functions/ThreadAwareSecurityManager.java)
- [no explicit logback in cassandra-all-3.9](https://github.com/apache/cassandra/blob/cassandra-3.9/src/java/org/apache/cassandra/cql3/functions/ThreadAwareSecurityManager.java)
- [minimum version of cassandra-all that doesn't have …
=> Upgrade to akka-persistence-cassandra:0.29 and cassandra-all:3.9

build.sbt, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActor.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/akka/rest/EventRoute.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/protobuf/EventEnvelopeSerializer.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActorSpec.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/akka/rest/EventRouteIntegrationSpec.java, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3.java, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3Backup.java, ts-reaktive-backup/src/main/java/com/tradeshift/reaktive/backup/S3Restore.java, ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/S3BackupSpec.java, ts-reaktive-backup/src/test/java/com/tradeshift/reaktive/backup/S3RestoreSpec.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/DataCenter.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/DataCenterForwarder.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/Replication.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActor.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/io/WebSocketDataCenterClient.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/DataCenterForwarderSpec.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/FakeRemoteTestActor.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/ReplicationIntegrationSpec.java, ts-reaktive-testkit/src/main/java/com/tradeshift/reaktive/testkit/AkkaPersistence.java
We now also postfix _2.12 and _2.11 for the Java artifacts, since they
can transiently depend on something that does bring in Scala.
=> Upgrade to akka to 2.5.4, and related libraries.

ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/DataCenterForwarder.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/EventClassifier.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/Visibility.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/VisibilityRepository.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActor.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/DataCenterForwarderSpec.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/ReplicationIntegrationSpec.java
Which will also automatically pick up new datacenters as they are added
(after a restart, of course)
=> Allow a "*" datacenter to indicate replication to everywhere

build.sbt, ts-reaktive-akka/src/main/java/com/tradeshift/reaktive/throttle/RateLimitExceededRejection.java, ts-reaktive-akka/src/main/java/com/tradeshift/reaktive/throttle/ThrottleActor.java, ts-reaktive-akka/src/main/java/com/tradeshift/reaktive/throttle/ThrottleDirective.java, ts-reaktive-akka/src/test/java/com/tradeshift/reaktive/akka/ThrottleDirectiveSpec.java, ts-reaktive-akka/src/test/resources/ThrottleDirectiveSpec.conf, ts-reaktive-akka/src/test/resources/log4j.xml
The new ThrottleDirective can be used to rate limit API calls while
distinguishing different users by a String value. This value is
application-specific and can be anything (IP address, username, ...)
The rate limiting is applied across the whole cluster by using cluster
sharding.
=> Add an API rate limiting directive

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/PersistentActorSharding.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActorSharding.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/NonReplicatedTestActor.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/ReplicatedTestActor.java
By simplifying the lambda that goes into PersistentActorSharding,
implementations can decide on their own rules of prefixing persistenceIds.
This also isolates the code that does the reverse a lot better.
=> Make PersistentActorSharding less smart, and have impl decide on prefix

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractCommandHandler.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActor.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActorSpec.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActor.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/NonReplicatedTestActor.java, ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/ReplicatedTestActor.java
When implementing actors, we are seeing more and more async "setup" code
needing to do checks, pull in extra information, etc, taking place before
the real Handler is invoked. This asyncronous activity should ideally
be part of the Handler class itself.
This commit re-defines AbstractCommandHandler as a partial function from
(Command, State) to CompletionStage(Results), where Results encapsulates
what was previously in AbstractCommandHandler.
Existing implementations need to rework their code, with examples present
in the changes to ReplicatedTestActor, NonReplicatedTestActor and
AbstractStatefulPersistentActorSpec in this commit.
=> Make command handlers asynchronous-first

ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/VisibilityCassandraSession.java
The asScalaBuffer method on JavaConversion was introduced in Scala 2.12
with the AsScalaConverters trait, so it's not available in 2.11.
=> Revert part of e9d0552 since it breaks 2.11 compatibility

ts-reaktive-replication/src/test/resources/log4j.xml
Since the current amount of logging causes timeout for the integration
test sometimes.
=> Reduce logging when testing ts-reaktive-replication

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/akka/rest/EventRoute.java
Make the eventRoute methods protected in order
to re-use them in plugins event routes.
=> [DOCPIPE-407] Make the EventRoute methods protected

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/protobuf/DelimitedProtobufFraming.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/protobuf/DelimitedProtobufFramingSpec.java
While parsing delimited protobuf messages, when a 'message size' value spans to multiple bytes, some existing deframed messages are not emitted.
This commit fixes the issue by keeping the state of the deframed buffer between stream graph stage invocations.
=> Fix delimited protobuf parsing issue.

ts-reaktive-marshal/src/main/java/com/tradeshift/reaktive/json/ObjectWriteProtocol.java
ObjectWriteProtocol was casting its inner arguments to Protocol (instead
of WriteProtocol), causing JSONProtocol.object() not to be usable with
write-only protocols. This commit fixes that.
=> Fix blind cast to the wrong type

ts-reaktive-marshal-akka/src/main/java/com/tradeshift/reaktive/marshal/stream/SchemaValidatorFlow.java
By default, RepointableActorRef logs an ERROR if a graph stage throws an
exception.
Rather, just fail the stage (using failStage()), and whoever is running
the graph can decide what to do with the exception.
=> Don't log an error when XSD validation fails

build.sbt, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/ACL.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/acl/GroupedUserACL.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerMetrics.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerWorkers.java, ts-reaktive-actors/src/main/protobuf/MaterializerActor.proto, ts-reaktive-actors/src/main/resources/reference.conf, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/MaterializerActorSpec.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/MaterializerWorkersSpec.java
The materializer now can run multiple worker streams in parallel, with
each stream having its own end timestamp to start processing. This
allows large event journals to prioritize importing recent events, while
still allowing all historic events to be read as well.
=> Allow multiple workers in MaterializerActor

build.sbt, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerWorkers.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/Generators.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/MaterializerActorSpec.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/MaterializerWorkersSpec.java, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/MaterializerWorkersTheories.java
Specifying an endTimestamp is handy when not everything before the first
worker needs to be reindexed.
The query API can be used to keep an eye on workers' progress, and react
when workers complete.
=> Allow endTimestamp for new workers, and add query API

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerMetrics.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerWorkers.java, ts-reaktive-actors/src/main/resources/reference.conf, ts-reaktive-actors/src/test/java/com/tradeshift/reaktive/materialize/MaterializerWorkersTheories.java
The statistic type for the time-based worker stats was wrong: since it's
a slow-changing value with only 1 global value, all of those should be
"Gauge" type and not "Histogram". An additional problem is that
histograms, by default, are limited to 2.1E12 as maximum value, which is
no good for time stamps.
We also reimplement "Reset" functionality, so we can easily trigger a
complete reimport; but now, we retain any extra workers that are already
present.
=> Update kamon stats for multiple workers, and implement reset

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java, ts-reaktive-actors/src/main/resources/reference.conf
We'd hardcoded it to 25 before which is appropriate for most journals, but probably is better left being configurable.
=> Make delete messages interval configurable

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerMetrics.java
The only base tag attached to all MaterializerActor metrics is the class
name of the actor. This can lead to duplicate metric names
if a single subclass is instantiated multiple times to do different
materializations. To remedy this and also facilitate further adjustments
of metric tags, this commit adds a protected method so that the
subclasses can introduce new tags to the metrics.
=> Enable addition of custom tags to MaterializerActor metrics

ts-reaktive-replication/src/test/java/com/tradeshift/reaktive/replication/ReplicationIntegrationSpec.java
The replication test currently is very unreliable, because it actually
starts 4 separate cassandra instances. Until we have time to simply run
it against one (in different keyspaces for each ActorSystem), let's
disable the "simple" variant of the test. That way, we at least cut it
down to only 2 cassandra instances.
=> Skip the simple variant of replication test

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/actors/AbstractStatefulPersistentActor.java, ts-reaktive-replication/src/main/java/com/tradeshift/reaktive/replication/actors/ReplicatedActor.java
The base AbstractStatefulPersistentActor class stashes further commands
while handling (the async part of) a command. However, subclasses may do
additional asynchronous actions before even handing a command down to
it.
Currently, there's no way for subclasses to postpone actions if a
command is already in progress.
This commit exposes `isCommandInProgress()`, which subclasses can use to
postpone (by stashing) incoming messages when an actual command is
already behind handled.
The commit also adds a missing log message when the first actual command
isn't actually handled by the subclass' implementation of
`createReceive()`, and removes a FIXME that has since been implemented.
=> Allow subclasses to hold off on commands while not idle 

ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerActor.java, ts-reaktive-actors/src/main/java/com/tradeshift/reaktive/materialize/MaterializerMetrics.java
Some monitoring systems could be repeating the last-known metric for a
stopped worker. By sending actual metrics on the number of workers (and
the number of actual streams), we will be able to better follow what's
really going on.
=> Keep metrics on number of workers, and number of actual streams
